# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: bookoteka.bookoteka
PackageVersion: 1.0.1
PackageLocale: pl-PL
Publisher: bookoteka
PublisherUrl: https://github.com/bookoteka
PublisherSupportUrl: https://github.com/bookoteka/bookoteka/issues
PackageName: bookoteka
PackageUrl: https://github.com/bookoteka/bookoteka
License: Proprietary
ShortDescription: Kompleksowa aplikacja na komputer służąca do śledzenia przeczytanych książek
ReleaseNotesUrl: https://github.com/bookoteka/bookoteka/releases/tag/v1.0.1
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/bookoteka/bookoteka/wiki
ManifestType: defaultLocale
ManifestVersion: 1.12.0
